### ISSUE TITLE
Separate output directories

### ISSUE THREAD

**Issue by getsnoopy** [TWCable/gradle-plugin-scr#8]
It seems like since Gradle 4.x, Gradle expects the JVM language code to be output to different classes directories. Could someone update the code to account for this?

Stacktrace:
```
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
        at org.gradle.api.internal.tasks.DefaultSourceSetOutput.getClassesDir(DefaultSourceSetOutput.java:80)
        at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getClassesDir(Unknown Source)
        at com.twcable.gradle.scr.ScrPlugin$_addScrTask_closure1$_closure3.doCall(ScrPlugin.groovy:44)
```

The issue and its solution are described in a [Stackoverflow post](https://stackoverflow.com/a/44894025/4717783).

**Comment by jdigger** [comment]
Thanks. I'll have to set aside some time to do that.
